library(RMySQL)
con<-dbConnect(MySQL(),user='advertising',password='advertising@654321',dbname='advertising',host='10.10.1.9')
#dbRemoveTable(con,"forecast")
stocks<-dbGetQuery(con,"select access_num from moviezongyitv_access_num where operation='vv' order by day")
dbDisconnect(con)
ve = as.vector(unlist(stocks))
prop=ts(ve)
plot(prop,xlab="time",ylab="given data")
ch=log(prop)
model=arima(ch,order=c(7,2,7),method="ML")
tsdiag(model)
model
prop.fore=predict(model,n.ahead=30)
ts.plot(prop,exp(prop.fore$pred),col=1:2,xlab="time",ylab="Observation: Z") 
re=exp(prop.fore$pred)
nn=as.integer(re)
date = Sys.Date()
dates=c(date,date+1:29)
days=as.character(dates)
dd=c(1:30)
df<-data.frame(id=dd,day=days,num=nn)
con<-dbConnect(MySQL(),user='advertising',password='advertising@654321',dbname='advertising',host='10.10.1.9')
dbWriteTable(con,"forecast",df,overwrite=T,field.types=list(id="int(255)",day="varchar(10)",num="bigint(30)"),row.names=F)
dbDisconnect(con)

